version: '2'

networks:
  default:

services:

  orderer.tracechain.com:
    image: hyperledger/fabric-orderer:${IMAGE_TAG}
    container_name: orderer.tracechain.com
    tty: true
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/tracechain.com/orderers/orderer.tracechain.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/tracechain.com/orderers/orderer.tracechain.com/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      default:
        aliases:
          - orderer.tracechain.com

  ca.manufacturer.tracechain.com:
    image: hyperledger/fabric-ca:${IMAGE_TAG}
    container_name: ca.manufacturer.tracechain.com
    tty: true
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.manufacturer.tracechain.com
      #- FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manufacturer.tracechain.com-cert.pem
      #- FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5da5c8049a9ec349ec4447c82a9c0f7db75b84012a78954ef083a9c9e4a9fa25_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      #- FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manufacturer.tracechain.com-cert.pem
      #- FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/5da5c8049a9ec349ec4447c82a9c0f7db75b84012a78954ef083a9c9e4a9fa25_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/manufacturer.tracechain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      default:
        aliases:
          - ca.manufacturer.tracechain.com

  peer0.manufacturer.tracechain.com:
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    container_name: peer0.manufacturer.tracechain.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:amd64-1.4.0
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.14
      - CORE_CHAINCODE_EXECUTETIMEOUT=120s
      - CORE_VM_DOCKER_ATTACHSTDOUT=false
      #- CORE_PEER_NETWORKID=tracechain
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer0.manufacturer.tracechain.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer0.manufacturer.tracechain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manufacturer.tracechain.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer0.manufacturer.tracechain.com
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/manufacturer.tracechain.com/peers/peer0.manufacturer.tracechain.com/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/manufacturer.tracechain.com/peers/peer0.manufacturer.tracechain.com/tls:/var/hyperledger/tls
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.tracechain.com
    links:
      - orderer.tracechain.com
    networks:
      default:
        aliases:
          - peer0.manufacturer.tracechain.com

  peer1.manufacturer.tracechain.com:
    image: hyperledger/fabric-peer:${IMAGE_TAG}
    container_name: peer1.manufacturer.tracechain.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:amd64-1.4.0
      - CORE_CHAINCODE_GOLANG_RUNTIME=hyperledger/fabric-baseos:amd64-0.4.14
      - CORE_CHAINCODE_EXECUTETIMEOUT=120s
      - CORE_VM_DOCKER_ATTACHSTDOUT=false
      #- CORE_PEER_NETWORKID=tracechain
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_ID=peer1.manufacturer.tracechain.com
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_ADDRESS=peer1.manufacturer.tracechain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.manufacturer.tracechain.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=peer1.manufacturer.tracechain.com
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/manufacturer.tracechain.com/peers/peer1.manufacturer.tracechain.com/msp:/var/hyperledger/msp
      - ./crypto-config/peerOrganizations/manufacturer.tracechain.com/peers/peer1.manufacturer.tracechain.com/tls:/var/hyperledger/tls
    ports:
      - 7151:7051
      - 7153:7053
    depends_on:
      - orderer.tracechain.com
    links:
      - orderer.tracechain.com
    networks:
      default:
        aliases:
          - peer1.manufacturer.tracechain.com